# ==========================================
# CẤU HÌNH SERVER
# ==========================================
server.port=8080

# ==========================================
# CẤU HÌNH KẾT NỐI SQL SERVER (TÀI KHOẢN SA)
# ==========================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=utetra_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# CẤU HÌNH JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CẤU HÌNH THYMELEAF
# ==========================================
spring.thymeleaf.cache=false

# ==========================================
# CẤU HÌNH GỬI MAIL (GMAIL SMTP) - KHẮC PHÚC LỖI THIẾU BEAN JAVAMAILSENDER
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tungnemc@gmail.com
spring.mail.password=loox ffup dxki pmdw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true